/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TransactionRequest } from '../model/models';
import { TransactionResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TransactionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param transactionRequest 
     */
    register(transactionRequest: TransactionRequest, extraHttpRequestParams?: any): Observable<TransactionResponse>;

}
