/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionResponse { 
    id?: number;
    type?: TransactionResponseTypeEnum;
    amount?: number;
    createdAt?: string;
    accountId?: number;
}
export enum TransactionResponseTypeEnum {
    Deposit = 'DEPOSIT',
    Withdrawal = 'WITHDRAWAL'
};



